name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
      
    - name: Setup MSBuild.exe
      
      uses: warrenbuckley/Setup-MSBuild@v1

   # - name: MSBuild
    #  working-directory: HelloWorld
     # run: msbuild HelloWorld.csproj
