name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Setup MSBuild.exe
      
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild
      working-directory: HelloWorld
      run: msbuild HelloWorld.csproj
      
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true      
