name: ASP.NET CII

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl https://api.github.com/repos/miteshNeema/MavenDemo/issues | jq '.[] | {Issuetitle: .title, Issuestate: .state, Id: .id, IssueOpenedBy: .user.login, Issued Date: .created_at}' 
       
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
