name: API FOR ISSUES REQUEST

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl https://api.github.com/repos/miteshNeema/MavenDemo/issues | jq '.[] | {Issue_title: .title, Issue_state: .state, Issue_Number: .id, Issue_Opened_By: .user.login, Issued_Date: .created_at}' >> "./output.json"
        sed 's/}/},/g' ./output.json >> "./outputFinal.json"
        sed '$ s/.$//' ./outputFinal.json >> "./outputFinal2.json"
       
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: outputFinal2
#     - name: Download a single artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: artifact
#         path : './commit1.json'
    - uses: azure/login@v1
      name: Azure Portal Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v1
      name: Azure SQL DB Login
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './SQLGitHub.dacpac' 
#     - run: |
#         cd /home/runner/work/sample-java-project/sample-java-project/
#         ls -ltr
#         echo "After "
    - uses: fixpoint/azblob-upload-artifact@v4
      name: Upload Artifact to Blob Storage
      with:
       connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
       name: Blob
       path: '/home/runner/work/HelloWorldDotNet/HelloWorldDotNet/commit.json'
    - uses: azure/sql-action@v1
      name: SQL Insert Query to Export Data from JSON 
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: './ExportJson.sql'
