name: TEST PULL REQUEST API

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       #curl https://api.github.com/repos/miteshNeema/MavenDemo/pulls?state=open | jq '.[] | {Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers, Approvers: .assignees}' >> "./output.json"
       echo "TAG_NAME=$(curl \
       -H "Accept: application/vnd.github.v3+json" \
       https://api.github.com/repos/mangeshpa/HelloWorldDotNet/stats/participation | jq '.["all"] | add')" 
       echo "$TAG_NAME"
       curl https://api.github.com/repos/miteshNeema/MavenDemo/pulls?state=open | jq '.[] | {Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers, Approvers: .assignees, No_Of_Commits:echo ${{TAG_NAME}}}' #>> "./output.json"
